sudo: required
services:
  - docker

before_install:
  - docker build -t swissjoshua/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true swissjoshua/react-test npm test -- --coverage

after_success:
  - docker build -t swissjoshua/multi-client ./client
  - docker build -t swissjoshua/multi-nginx ./nginx
  - docker build -t swissjoshua/multi-api ./api
  - docker build -t swissjoshua/multi-worker ./worker

  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to Docker Hub
  - docker push swissjoshua/multi-client
  - docker push swissjoshua/multi-nginx
  - docker push swissjoshua/multi-api
  - docker push swissjoshua/multi-worker
